import webbrowser
import os
import re
import json
from urllib.request import Request, urlopen
print('by Affe#1914')
klasse = input('1.klasse (1)   2.klasse (2)   3.klasse (3)    4.klasse (4)   5.klasse (5)   6.klasse (6)   7.klasse (7)   8.klasse (8)   9.klasse (9)   10.klasse (10)\
nachhilfe (nachhilfe)   jitsi_website (main)   verschiedene_fächer (fächer)')
                




#die klassen
def klasse1():
    webbrowser. open('https://meet.jit.si/1')
    webbrowser. open('https://meet.jit.si/1a')
    webbrowser. open('https://meet.jit.si/1b')
    webbrowser. open('https://meet.jit.si/1c')
    webbrowser. open('https://meet.jit.si/1d')
    webbrowser. open('https://meet.jit.si/1e')
    webbrowser. open('https://meet.jit.si/1f')
    webbrowser. open('https://meet.jit.si/klasse1a')
    webbrowser. open('https://meet.jit.si/klasse1b')
    webbrowser. open('https://meet.jit.si/klasse1c')
    webbrowser. open('https://meet.jit.si/klasse1d')
    webbrowser. open('https://meet.jit.si/klasse1e')
    webbrowser. open('https://meet.jit.si/klasse1f')
    webbrowser. open('https://meet.jit.si/videokonferenz1a')
    webbrowser. open('https://meet.jit.si/videokonferenz1b')
    webbrowser. open('https://meet.jit.si/videokonferenz1c')
    webbrowser. open('https://meet.jit.si/videokonferenz1d')
    webbrowser. open('https://meet.jit.si/videokonferenz1e')
    webbrowser. open('https://meet.jit.si/videokonferenz1f')
def klasse2():
    webbrowser. open('https://meet.jit.si/2')
    webbrowser. open('https://meet.jit.si/2a')
    webbrowser. open('https://meet.jit.si/2b')
    webbrowser. open('https://meet.jit.si/2c')
    webbrowser. open('https://meet.jit.si/2d')
    webbrowser. open('https://meet.jit.si/2e')
    webbrowser. open('https://meet.jit.si/2e')
    webbrowser. open('https://meet.jit.si/klasse2a')
    webbrowser. open('https://meet.jit.si/klasse2b')
    webbrowser. open('https://meet.jit.si/klasse2c')
    webbrowser. open('https://meet.jit.si/klasse2d')
    webbrowser. open('https://meet.jit.si/klasse2e')
    webbrowser. open('https://meet.jit.si/klasse2f')
    webbrowser. open('https://meet.jit.si/videokonferenz2a')
    webbrowser. open('https://meet.jit.si/videokonferenz2b')
    webbrowser. open('https://meet.jit.si/videokonferenz2c')
    webbrowser. open('https://meet.jit.si/videokonferenz2d')
    webbrowser. open('https://meet.jit.si/videokonferenz2e')
    webbrowser. open('https://meet.jit.si/videokonferenz2f')
def klasse3():
    webbrowser. open('https://meet.jit.si/3')
    webbrowser. open('https://meet.jit.si/3a')
    webbrowser. open('https://meet.jit.si/3b')
    webbrowser. open('https://meet.jit.si/3c')
    webbrowser. open('https://meet.jit.si/3d')
    webbrowser. open('https://meet.jit.si/3e')
    webbrowser. open('https://meet.jit.si/3f')
    webbrowser. open('https://meet.jit.si/klasse3a')
    webbrowser. open('https://meet.jit.si/klasse3b')
    webbrowser. open('https://meet.jit.si/klasse3c')
    webbrowser. open('https://meet.jit.si/klasse3d')
    webbrowser. open('https://meet.jit.si/klasse3e')
    webbrowser. open('https://meet.jit.si/klasse3f')
    webbrowser. open('https://meet.jit.si/videokonferenz3a')
    webbrowser. open('https://meet.jit.si/videokonferenz3b')
    webbrowser. open('https://meet.jit.si/videokonferenz3c')
    webbrowser. open('https://meet.jit.si/videokonferenz3d')
    webbrowser. open('https://meet.jit.si/videokonferenz3e')
    webbrowser. open('https://meet.jit.si/videokonferenz3f')
def klasse4():
    webbrowser. open('https://meet.jit.si/4')
    webbrowser. open('https://meet.jit.si/4a')
    webbrowser. open('https://meet.jit.si/4b')
    webbrowser. open('https://meet.jit.si/4c')
    webbrowser. open('https://meet.jit.si/4d')
    webbrowser. open('https://meet.jit.si/4e')
    webbrowser. open('https://meet.jit.si/4f')
    webbrowser. open('https://meet.jit.si/klasse4a')
    webbrowser. open('https://meet.jit.si/klasse4b')
    webbrowser. open('https://meet.jit.si/klasse4c')
    webbrowser. open('https://meet.jit.si/klasse4d')
    webbrowser. open('https://meet.jit.si/klasse4e')
    webbrowser. open('https://meet.jit.si/klasse4f')
    webbrowser. open('https://meet.jit.si/videokonferenz4a')
    webbrowser. open('https://meet.jit.si/videokonferenz4b')
    webbrowser. open('https://meet.jit.si/videokonferenz4c')
    webbrowser. open('https://meet.jit.si/videokonferenz4d')
    webbrowser. open('https://meet.jit.si/videokonferenz4e')
    webbrowser. open('https://meet.jit.si/videokonferenz4f')
def klasse5():
    webbrowser. open('https://meet.jit.si/5')
    webbrowser. open('https://meet.jit.si/5a')
    webbrowser. open('https://meet.jit.si/5b')
    webbrowser. open('https://meet.jit.si/5c')
    webbrowser. open('https://meet.jit.si/5d')
    webbrowser. open('https://meet.jit.si/5e')
    webbrowser. open('https://meet.jit.si/5f')
    webbrowser. open('https://meet.jit.si/klasse5a')
    webbrowser. open('https://meet.jit.si/klasse5b')
    webbrowser. open('https://meet.jit.si/klasse5c')
    webbrowser. open('https://meet.jit.si/klasse5d')
    webbrowser. open('https://meet.jit.si/klasse5e')
    webbrowser. open('https://meet.jit.si/klasse5f')
    webbrowser. open('https://meet.jit.si/videokonferenz5a')
    webbrowser. open('https://meet.jit.si/videokonferenz5b')
    webbrowser. open('https://meet.jit.si/videokonferenz5c')
    webbrowser. open('https://meet.jit.si/videokonferenz5d')
    webbrowser. open('https://meet.jit.si/videokonferenz5e')
    webbrowser. open('https://meet.jit.si/videokonferenz5f')
def klasse6():
    webbrowser. open('https://meet.jit.si/6')
    webbrowser. open('https://meet.jit.si/6a')
    webbrowser. open('https://meet.jit.si/6b')
    webbrowser. open('https://meet.jit.si/6c')
    webbrowser. open('https://meet.jit.si/6d')
    webbrowser. open('https://meet.jit.si/6e')
    webbrowser. open('https://meet.jit.si/6f')
    webbrowser. open('https://meet.jit.si/klasse6a')
    webbrowser. open('https://meet.jit.si/klasse6b')
    webbrowser. open('https://meet.jit.si/klasse6c')
    webbrowser. open('https://meet.jit.si/klasse6d')
    webbrowser. open('https://meet.jit.si/klasse6e')
    webbrowser. open('https://meet.jit.si/klasse6f')
    webbrowser. open('https://meet.jit.si/videokonferenz6a')
    webbrowser. open('https://meet.jit.si/videokonferenz6b')
    webbrowser. open('https://meet.jit.si/videokonferenz6c')
    webbrowser. open('https://meet.jit.si/videokonferenz6d')
    webbrowser. open('https://meet.jit.si/videokonferenz6e')
    webbrowser. open('https://meet.jit.si/videokonferenz6f')
def klasse7():
    webbrowser. open('https://meet.jit.si/7')
    webbrowser. open('https://meet.jit.si/7a')
    webbrowser. open('https://meet.jit.si/7b')
    webbrowser. open('https://meet.jit.si/7c')
    webbrowser. open('https://meet.jit.si/7d')
    webbrowser. open('https://meet.jit.si/7e')
    webbrowser. open('https://meet.jit.si/7f')
    webbrowser. open('https://meet.jit.si/klasse7a')
    webbrowser. open('https://meet.jit.si/klasse7b')
    webbrowser. open('https://meet.jit.si/klasse7c')
    webbrowser. open('https://meet.jit.si/klasse7d')
    webbrowser. open('https://meet.jit.si/klasse7e')
    webbrowser. open('https://meet.jit.si/klasse7f')
    webbrowser. open('https://meet.jit.si/videokonferenz7a')
    webbrowser. open('https://meet.jit.si/videokonferenz7b')
    webbrowser. open('https://meet.jit.si/videokonferenz7c')
    webbrowser. open('https://meet.jit.si/videokonferenz7d')
    webbrowser. open('https://meet.jit.si/videokonferenz7e')
    webbrowser. open('https://meet.jit.si/videokonferenz7f')
def klasse8():
    webbrowser. open('https://meet.jit.si/8')
    webbrowser. open('https://meet.jit.si/8a')
    webbrowser. open('https://meet.jit.si/8b')
    webbrowser. open('https://meet.jit.si/8c')
    webbrowser. open('https://meet.jit.si/8d')
    webbrowser. open('https://meet.jit.si/8e')
    webbrowser. open('https://meet.jit.si/8f')
    webbrowser. open('https://meet.jit.si/klasse8a')
    webbrowser. open('https://meet.jit.si/klasse8b')
    webbrowser. open('https://meet.jit.si/klasse8c')
    webbrowser. open('https://meet.jit.si/klasse8d')
    webbrowser. open('https://meet.jit.si/klasse8e')
    webbrowser. open('https://meet.jit.si/klasse8f')
    webbrowser. open('https://meet.jit.si/videokonferenz8a')
    webbrowser. open('https://meet.jit.si/videokonferenz8b')
    webbrowser. open('https://meet.jit.si/videokonferenz8c')
    webbrowser. open('https://meet.jit.si/videokonferenz8d')
    webbrowser. open('https://meet.jit.si/videokonferenz8e')
    webbrowser. open('https://meet.jit.si/videokonferenz8f')
def klasse9():
    webbrowser. open('https://meet.jit.si/9')
    webbrowser. open('https://meet.jit.si/9a')
    webbrowser. open('https://meet.jit.si/9b')
    webbrowser. open('https://meet.jit.si/9c')
    webbrowser. open('https://meet.jit.si/9d')
    webbrowser. open('https://meet.jit.si/9e')
    webbrowser. open('https://meet.jit.si/9f')
    webbrowser. open('https://meet.jit.si/klasse9a')
    webbrowser. open('https://meet.jit.si/klasse9b')
    webbrowser. open('https://meet.jit.si/klasse9c')
    webbrowser. open('https://meet.jit.si/klasse9d')
    webbrowser. open('https://meet.jit.si/klasse9e')
    webbrowser. open('https://meet.jit.si/klasse9f')
    webbrowser. open('https://meet.jit.si/videokonferenz9a')
    webbrowser. open('https://meet.jit.si/videokonferenz9b')
    webbrowser. open('https://meet.jit.si/videokonferenz9c')
    webbrowser. open('https://meet.jit.si/videokonferenz9d')
    webbrowser. open('https://meet.jit.si/videokonferenz9e')
    webbrowser. open('https://meet.jit.si/videokonferenz9f')
def klasse10():
    webbrowser. open('https://meet.jit.si/10')
    webbrowser. open('https://meet.jit.si/10a')
    webbrowser. open('https://meet.jit.si/10b')
    webbrowser. open('https://meet.jit.si/10c')
    webbrowser. open('https://meet.jit.si/10d')
    webbrowser. open('https://meet.jit.si/10e')
    webbrowser. open('https://meet.jit.si/10f')
    webbrowser. open('https://meet.jit.si/klasse10a')
    webbrowser. open('https://meet.jit.si/klasse10b')
    webbrowser. open('https://meet.jit.si/klasse10c')
    webbrowser. open('https://meet.jit.si/klasse10d')
    webbrowser. open('https://meet.jit.si/klasse10e')
    webbrowser. open('https://meet.jit.si/klasse10f')
    webbrowser. open('https://meet.jit.si/videokonferenz10a')
    webbrowser. open('https://meet.jit.si/videokonferenz10b')
    webbrowser. open('https://meet.jit.si/videokonferenz10c')
    webbrowser. open('https://meet.jit.si/videokonferenz10d')
    webbrowser. open('https://meet.jit.si/videokonferenz10e')
    webbrowser. open('https://meet.jit.si/videokonferenz10f')
def website():
    webbrowser. open('https://meet.jit.si/')
def fächer():
    webbrowser. open('https://meet.jit.si/mathe')
    webbrowser. open('https://meet.jit.si/deutsch')
    webbrowser. open('https://meet.jit.si/englisch')
    webbrowser. open('https://meet.jit.si/bio')
    webbrowser. open('https://meet.jit.si/biologie')
    webbrowser. open('https://meet.jit.si/chemie')
    webbrowser. open('https://meet.jit.si/physik')
    webbrowser. open('https://meet.jit.si/latein')
    webbrowser. open('https://meet.jit.si/schule')
def nachhilfe():
    webbrowser. open('https://meet.jit.si/nachhilfe')
    webbrowser. open('https://meet.jit.si/nachhilfedeutsch')
    webbrowser. open('https://meet.jit.si/nachhilfemathe')
    webbrowser. open('https://meet.jit.si/nachhilfeenglisch')
if klasse == '1':
    klasse1()
elif klasse == '2':
    klasse2()
elif klasse == '3':
    klasse3()
elif klasse == '4':
    klasse4()
elif klasse == '5':
    klasse5()
elif klasse == '6':
    klasse6()
elif klasse == '7':
    klasse7()
elif klasse == '8':
    klasse8()
elif klasse == '9':
    klasse9()
elif klasse == '10':
    klasse10()
elif klasse == 'main':
    website()
elif klasse == 'fächer':
    fächer()
elif klasse == 'nachhilfe':
    nachhilfe()
else:
    print('?')

